apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-backend
  template:
    metadata:
      labels:
        app: django-backend
    spec:
      containers:
        - name: django-backend
          image: photoappacr.azurecr.io/django-backend:v16
          ports:
            - containerPort: 8000
          env:
            # --- Django Core Settings ---
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secret
                  key: SECRET_KEY
            - name: DEBUG
              value: "False"

            # --- Database Settings (Names match settings.py) ---
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pgsql-secret
                  key: DB_HOST

            # --- Azure Storage Settings (Names match settings.py) ---
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: blob-secret
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: blob-secret
                  key: AZURE_STORAGE_CONNECTION_STRING
            - name: AZURE_CONTAINER_STATIC
              valueFrom:
                secretKeyRef:
                  name: blob-secret
                  key: AZURE_CONTAINER_STATIC
            - name: AZURE_CONTAINER_MEDIA
              valueFrom:
                secretKeyRef:
                  name: blob-secret
                  key: AZURE_CONTAINER_MEDIA
