apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
type: Opaque
data:
  DB_NAME: cGhvdG9kYnNlcnZlcg==
  DB_USER: cGdhZG1pbg==
  DB_PASSWORD: R2FsbGVyeUFwcDIwMjUh
  DB_HOST: cGhvdG9kYnNlcnZlci5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20=
