apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: photoappacr.azurecr.io/react-frontend:v12
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://django-backend:8000" # Internal cluster DNS for your Django service
